[package]
name = "rustario_2d"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = {version ="0.4.5", features = ["audio"]}
image = "0.25.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4.0"

